In [1]:
import sys
import boto3
import pyarrow
import pandas as pd
import pyarrow.parquet as pq

MINIO_ENDPOINT = "http://minio:9000"  # DENTRO do container
ACCESS_KEY = "minio"
SECRET_KEY = "minio123"

import pyarrow.fs as fs

fs_s3 = fs.S3FileSystem(
    endpoint_override=MINIO_ENDPOINT,
    access_key=ACCESS_KEY,
    secret_key=SECRET_KEY,
    scheme="http"
)
fs_s3.get_file_info(fs.FileSelector(""))

[<FileInfo for 'bronze': type=FileType.Directory>,
 <FileInfo for 'gold': type=FileType.Directory>,
 <FileInfo for 'silver': type=FileType.Directory>]

In [2]:
def load_parquet(path):
    return pq.ParquetDataset(
        path,
        filesystem=fs_s3
    ).read_pandas().to_pandas()

## carregar as bases
df_sinistros = load_parquet("silver/infosiga/sinistros_2015-2021/dt=2026-04-25/sinistros_2015-2021.parquet")

df_pessoas = load_parquet("silver/infosiga/pessoas_2015-2021/dt=2026-04-25/pessoas_2015-2021.parquet")

df_veiculos = load_parquet("silver/infosiga/veiculos_2015-2021/dt=2026-04-25/veiculos_2015-2021.parquet")

df_pessoas.shape, df_veiculos.shape, df_sinistros.shape

((475178, 29), (633113, 12), (535566, 48))

In [17]:
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [18]:
df_pessoas[['id_sinistro', 'id_veiculo', 'cod_ibge', 'municipio',
       'regiao_administrativa', 'tipo_via', 'tipo_veiculo_vitima', 'sexo',
       'idade', 'gravidade_lesao', 'tipo_de_vitima',
       'faixa_etaria_demografica', 'faixa_etaria_legal', 'profissao',
       'grau_de_instrucao', 'nacionalidade', 'data_sinistro', 'ano_sinistro',
       'mes_sinistro', 'dia_sinistro', 'ano_mes_sinistro', 'data_obito',
       'ano_obito', 'mes_obito', 'dia_obito', 'ano_mes_obito', 'local_obito',
       'local_via', 'tempo_sinistro_obito']].head()

   id_sinistro  id_veiculo  cod_ibge            municipio regiao_administrativa             tipo_via tipo_veiculo_vitima       sexo  idade gravidade_lesao  tipo_de_vitima faixa_etaria_demografica faixa_etaria_legal             profissao grau_de_instrucao nacionalidade data_sinistro  ano_sinistro  mes_sinistro  dia_sinistro ano_mes_sinistro  data_obito  ano_obito  mes_obito  dia_obito ano_mes_obito               local_obito local_via  tempo_sinistro_obito
0      2473612         NaN   3509957                CANAS   SÃO JOSÉ DOS CAMPOS  ESTRADAS E RODOVIAS           AUTOMOVEL  MASCULINO   24.0           FATAL      PASSAGEIRO                  20 a 24              18-24                  None              None          None    01/01/2015          2015             1             1          2015/01  01/01/2015     2015.0        1.0        1.0       2015/01                       VIA   PUBLICO                   0.0
1      2460453         NaN   3543402       RIBEIRAO PRETO        RIBEIRÃO PRETO         VIAS URBANAS                None  MASCULINO   68.0           FATAL        PEDESTRE                  65 a 69              65-69                  None              None          None    03/01/2015          2015             1             3          2015/01  03/01/2015     2015.0        1.0        3.0       2015/01  ESTABELECIMENTO DE SAUDE   PUBLICO                   0.0
2      2457878         NaN   3505500             BARRETOS              BARRETOS  ESTRADAS E RODOVIAS            CAMINHAO   FEMININO   54.0           FATAL      PASSAGEIRO                  50 a 54              50-54                  None              None          None    05/01/2015          2015             1             5          2015/01  05/01/2015     2015.0        1.0        5.0       2015/01                       VIA   PUBLICO                   0.0
3      2476044         NaN   3552205             SOROCABA              SOROCABA  ESTRADAS E RODOVIAS                None   FEMININO   43.0  NAO DISPONIVEL  NAO DISPONIVEL                  40 a 44              40-44  AUXILIAR DE PRODUCAO              None          None    09/01/2015          2015             1             9          2015/01        None        NaN        NaN        NaN          None                      None   PUBLICO                   NaN
4      2476271         NaN   3549904  SAO JOSE DOS CAMPOS   SÃO JOSÉ DOS CAMPOS         VIAS URBANAS                None  MASCULINO   27.0  NAO DISPONIVEL  NAO DISPONIVEL                  25 a 29              25-29                  None              None          None    10/01/2015          2015             1            10          2015/01        None        NaN        NaN        NaN          None                      None   PUBLICO                   NaN

In [7]:
df_veiculos.head(3)
id_sinistro	id_veiculo	marca_modelo	ano_fab	ano_modelo	cor_veiculo	tipo_veiculo	data_sinistro	ano_sinistro	mes_sinistro	dia_sinistro	ano_mes_sinistro
0	2501575	72104	None	NaN	NaN	None	OUTROS	21/12/2014	2014	12	21	2014/12
1	2456933	2281029	None	NaN	NaN	None	OUTROS	23/12/2014	2014	12	23	2014/12
2	2487781	50348	None	NaN	NaN	None	OUTROS	28/12/2014	2014	12	28	2014/12

,id_sinistro,id_veiculo,marca_modelo,ano_fab,ano_modelo,cor_veiculo,tipo_veiculo,data_sinistro,ano_sinistro,mes_sinistro,dia_sinistro,ano_mes_sinistro
0,2501575,72104,None,NaN,NaN,None,OUTROS,21/12/2014,2014,12,21,2014/12
1,2456933,2281029,None,NaN,NaN,None,OUTROS,23/12/2014,2014,12,23,2014/12
2,2487781,50348,None,NaN,NaN,None,OUTROS,28/12/2014,2014,12,28,2014/12

In [6]:
df_sinistros.head(3)
id_sinistro	tipo_registro	data_sinistro	ano_sinistro	mes_sinistro	dia_sinistro	hora_sinistro	ano_mes_sinistro	dia_da_semana	turno	...	tp_sinistro_colisao_traseira	tp_sinistro_colisao_lateral	tp_sinistro_colisao_transversal	tp_sinistro_colisao_outros	tp_sinistro_choque	tp_sinistro_capotamento	tp_sinistro_engavetamento	tp_sinistro_tombamento	tp_sinistro_outros	tp_sinistro_nao_disponivel
0	2501575	SINISTRO FATAL	21/12/2014	2014	12	21	20:00	2014/12	Domingo	NOITE	...	NaN	None	None	None	None	None	None	None	None	None
1	2462674	SINISTRO FATAL	31/12/2014	2014	12	31	22:53	2014/12	Quarta-feira	NOITE	...	NaN	None	None	None	None	None	None	None	None	None
2	2470843	SINISTRO FATAL	01/01/2015	2015	1	1	16:00	2015/01	Quinta-feira	TARDE	...	NaN	None	None	None	None	S	None	None	None	None

,id_sinistro,tipo_registro,data_sinistro,ano_sinistro,mes_sinistro,dia_sinistro,hora_sinistro,ano_mes_sinistro,dia_da_semana,turno,...,tp_sinistro_colisao_traseira,tp_sinistro_colisao_lateral,tp_sinistro_colisao_transversal,tp_sinistro_colisao_outros,tp_sinistro_choque,tp_sinistro_capotamento,tp_sinistro_engavetamento,tp_sinistro_tombamento,tp_sinistro_outros,tp_sinistro_nao_disponivel
0,2501575,SINISTRO FATAL,21/12/2014,2014,12,21,20:00,2014/12,Domingo,NOITE,...,NaN,None,None,None,None,None,None,None,None,None
1,2462674,SINISTRO FATAL,31/12/2014,2014,12,31,22:53,2014/12,Quarta-feira,NOITE,...,NaN,None,None,None,None,None,None,None,None,None
2,2470843,SINISTRO FATAL,01/01/2015,2015,1,1,16:00,2015/01,Quinta-feira,TARDE,...,NaN,None,None,None,None,S,None,None,None,None

In [4]:
df_pessoas.head()
id_sinistro	id_veiculo	cod_ibge	municipio	regiao_administrativa	tipo_via	tipo_veiculo_vitima	sexo	idade	gravidade_lesao	...	dia_sinistro	ano_mes_sinistro	data_obito	ano_obito	mes_obito	dia_obito	ano_mes_obito	local_obito	local_via	tempo_sinistro_obito
0	2473612	NaN	3509957	CANAS	SÃO JOSÉ DOS CAMPOS	ESTRADAS E RODOVIAS	AUTOMOVEL	MASCULINO	24.0	FATAL	...	1	2015/01	01/01/2015	2015.0	1.0	1.0	2015/01	VIA	PUBLICO	0.0
1	2460453	NaN	3543402	RIBEIRAO PRETO	RIBEIRÃO PRETO	VIAS URBANAS	None	MASCULINO	68.0	FATAL	...	3	2015/01	03/01/2015	2015.0	1.0	3.0	2015/01	ESTABELECIMENTO DE SAUDE	PUBLICO	0.0
2	2457878	NaN	3505500	BARRETOS	BARRETOS	ESTRADAS E RODOVIAS	CAMINHAO	FEMININO	54.0	FATAL	...	5	2015/01	05/01/2015	2015.0	1.0	5.0	2015/01	VIA	PUBLICO	0.0
3	2476044	NaN	3552205	SOROCABA	SOROCABA	ESTRADAS E RODOVIAS	None	FEMININO	43.0	NAO DISPONIVEL	...	9	2015/01	None	NaN	NaN	NaN	None	None	PUBLICO	NaN
4	2476271	NaN	3549904	SAO JOSE DOS CAMPOS	SÃO JOSÉ DOS CAMPOS	VIAS URBANAS	None	MASCULINO	27.0	NAO DISPONIVEL	...	10	2015/01	None	NaN	NaN	NaN	None	None	PUBLICO	NaN

,id_sinistro,id_veiculo,cod_ibge,municipio,regiao_administrativa,tipo_via,tipo_veiculo_vitima,sexo,idade,gravidade_lesao,...,dia_sinistro,ano_mes_sinistro,data_obito,ano_obito,mes_obito,dia_obito,ano_mes_obito,local_obito,local_via,tempo_sinistro_obito
0,2473612,NaN,3509957,CANAS,SÃO JOSÉ DOS CAMPOS,ESTRADAS E RODOVIAS,AUTOMOVEL,MASCULINO,24.0,FATAL,...,1,2015/01,01/01/2015,2015.0,1.0,1.0,2015/01,VIA,PUBLICO,0.0
1,2460453,NaN,3543402,RIBEIRAO PRETO,RIBEIRÃO PRETO,VIAS URBANAS,None,MASCULINO,68.0,FATAL,...,3,2015/01,03/01/2015,2015.0,1.0,3.0,2015/01,ESTABELECIMENTO DE SAUDE,PUBLICO,0.0
2,2457878,NaN,3505500,BARRETOS,BARRETOS,ESTRADAS E RODOVIAS,CAMINHAO,FEMININO,54.0,FATAL,...,5,2015/01,05/01/2015,2015.0,1.0,5.0,2015/01,VIA,PUBLICO,0.0
3,2476044,NaN,3552205,SOROCABA,SOROCABA,ESTRADAS E RODOVIAS,None,FEMININO,43.0,NAO DISPONIVEL,...,9,2015/01,None,NaN,NaN,NaN,None,None,PUBLICO,NaN
4,2476271,NaN,3549904,SAO JOSE DOS CAMPOS,SÃO JOSÉ DOS CAMPOS,VIAS URBANAS,None,MASCULINO,27.0,NAO DISPONIVEL,...,10,2015/01,None,NaN,NaN,NaN,None,None,PUBLICO,NaN

In [3]:
print("sinistros:", df_sinistros.shape)
print("pessoas:", df_pessoas.shape)
print("veiculos:", df_veiculos.shape)

print("\ncolunas-chave presentes?")
print("sinistros:", "id_sinistro" in df_sinistros.columns)
print("pessoas:", "id_sinistro" in df_pessoas.columns)
print("veiculos:", "id_sinistro" in df_veiculos.columns)

sinistros: (535566, 48)
pessoas: (475178, 29)
veiculos: (633113, 12)

colunas-chave presentes?
sinistros: True
pessoas: True
veiculos: True

In [5]:
import pandas as pd
import re
import unicodedata

def normalize_text(x):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return None
    s = str(x).strip()
    if s == "" or s.lower() in {"nan", "none"}:
        return None
    s = s.upper()
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"\s+", " ", s).strip()
    return s or None

def parse_date_br(series):
    return pd.to_datetime(series, dayfirst=True, errors="coerce")

def parse_time_hhmm(series):
    # retorna datetime.time
    dt = pd.to_datetime(series, format="%H:%M", errors="coerce")
    return dt.dt.time

In [6]:
print(normalize_text("São José  dos   Campos"))

SAO JOSE DOS CAMPOS

In [7]:
sin_prep = df_sinistros.copy()

# chave
sin_prep["id_sinistro"] = pd.to_numeric(sin_prep["id_sinistro"], errors="coerce").astype("Int64")
sin_prep = sin_prep.dropna(subset=["id_sinistro"])
sin_prep["id_sinistro"] = sin_prep["id_sinistro"].astype(int)

# datas/horas
if "data_sinistro" in sin_prep.columns:
    sin_prep["data_sinistro_dt"] = parse_date_br(sin_prep["data_sinistro"])
if "hora_sinistro" in sin_prep.columns:
    sin_prep["hora_sinistro_t"] = parse_time_hhmm(sin_prep["hora_sinistro"])

# normalizar dimensões-chave
for col in ["tipo_registro", "dia_da_semana", "turno", "ano_mes_sinistro"]:
    if col in sin_prep.columns:
        sin_prep[col] = sin_prep[col].apply(normalize_text)

# flag fatal
if "tipo_registro" in sin_prep.columns:
    sin_prep["is_fatal_sinistro"] = sin_prep["tipo_registro"].eq("SINISTRO FATAL")

# dedupe (1 linha por sinistro)
sin_prep = sin_prep.drop_duplicates(subset=["id_sinistro"])

In [8]:
print(sin_prep.shape)
sin_prep[["id_sinistro","tipo_registro","data_sinistro_dt","turno","is_fatal_sinistro"]].head(3)

(535566, 51)

   id_sinistro   tipo_registro data_sinistro_dt  turno  is_fatal_sinistro
0      2501575  SINISTRO FATAL       2014-12-21  NOITE               True
1      2462674  SINISTRO FATAL       2014-12-31  NOITE               True
2      2470843  SINISTRO FATAL       2015-01-01  TARDE               True

In [9]:
pes_prep = df_pessoas.copy()

pes_prep["id_sinistro"] = pd.to_numeric(pes_prep["id_sinistro"], errors="coerce").astype("Int64")
pes_prep = pes_prep.dropna(subset=["id_sinistro"])
pes_prep["id_sinistro"] = pes_prep["id_sinistro"].astype(int)

if "id_veiculo" in pes_prep.columns:
    pes_prep["id_veiculo"] = pd.to_numeric(pes_prep["id_veiculo"], errors="coerce").astype("Int64")

# normalizar textos relevantes
for col in ["municipio", "regiao_administrativa", "tipo_via", "tipo_veiculo_vitima", "sexo", "gravidade_lesao", "local_obito", "local_via"]:
    if col in pes_prep.columns:
        pes_prep[col] = pes_prep[col].apply(normalize_text)

# idade
if "idade" in pes_prep.columns:
    pes_prep["idade"] = pd.to_numeric(pes_prep["idade"], errors="coerce")

# data_obito
if "data_obito" in pes_prep.columns:
    pes_prep["data_obito_dt"] = parse_date_br(pes_prep["data_obito"])

# flag fatal na pessoa
if "gravidade_lesao" in pes_prep.columns:
    pes_prep["is_fatal_pessoa"] = pes_prep["gravidade_lesao"].eq("FATAL")

# faixa etária
def faixa_etaria(idade):
    if pd.isna(idade):
        return "NA"
    if idade < 18:
        return "MENOR_18"
    if idade < 30:
        return "18_29"
    if idade < 50:
        return "30_49"
    return "50+"

pes_prep["faixa_etaria"] = pes_prep["idade"].apply(faixa_etaria) if "idade" in pes_prep.columns else "NA"

# dedupe linhas idênticas
pes_prep = pes_prep.drop_duplicates()

In [10]:
print(pes_prep.shape)
pes_prep[["id_sinistro","municipio","tipo_via","sexo","idade","faixa_etaria","gravidade_lesao","is_fatal_pessoa"]].head(3)

(474530, 32)

,id_sinistro,municipio,tipo_via,sexo,idade,faixa_etaria,gravidade_lesao,is_fatal_pessoa
0,2473612,CANAS,ESTRADAS E RODOVIAS,MASCULINO,24.0,18_29,FATAL,True
1,2460453,RIBEIRAO PRETO,VIAS URBANAS,MASCULINO,68.0,50+,FATAL,True
2,2457878,BARRETOS,ESTRADAS E RODOVIAS,FEMININO,54.0,50+,FATAL,True

In [11]:
vei_prep = df_veiculos.copy()

vei_prep["id_sinistro"] = pd.to_numeric(vei_prep["id_sinistro"], errors="coerce").astype("Int64")
vei_prep = vei_prep.dropna(subset=["id_sinistro"])
vei_prep["id_sinistro"] = vei_prep["id_sinistro"].astype(int)

if "id_veiculo" in vei_prep.columns:
    vei_prep["id_veiculo"] = pd.to_numeric(vei_prep["id_veiculo"], errors="coerce").astype("Int64")

for col in ["marca_modelo", "cor_veiculo", "tipo_veiculo", "ano_mes_sinistro"]:
    if col in vei_prep.columns:
        vei_prep[col] = vei_prep[col].apply(normalize_text)

if "data_sinistro" in vei_prep.columns:
    vei_prep["data_sinistro_dt"] = parse_date_br(vei_prep["data_sinistro"])

vei_prep = vei_prep.drop_duplicates()

In [12]:
print(vei_prep.shape)
vei_prep[["id_sinistro","id_veiculo","tipo_veiculo","data_sinistro_dt"]].head(3)

(633113, 13)

   id_sinistro  id_veiculo tipo_veiculo data_sinistro_dt
0      2501575       72104       OUTROS       2014-12-21
1      2456933     2281029       OUTROS       2014-12-23
2      2487781       50348       OUTROS       2014-12-28

In [13]:
# agregados por sinistro
pes_agg = (
    pes_prep.groupby("id_sinistro", as_index=False)
            .agg(
                n_pessoas=("id_sinistro", "size"),
                n_fatais_pessoas=("is_fatal_pessoa", "sum") if "is_fatal_pessoa" in pes_prep.columns else ("id_sinistro", "size"),
            )
)
if "is_fatal_pessoa" not in pes_prep.columns:
    pes_agg["n_fatais_pessoas"] = 0

vei_agg = (
    vei_prep.groupby("id_sinistro", as_index=False)
            .agg(n_veiculos=("id_sinistro", "size"))
)

sinistros_enriched = (
    sin_prep.merge(pes_agg, on="id_sinistro", how="left")
            .merge(vei_agg, on="id_sinistro", how="left")
)

sinistros_enriched["n_pessoas"] = sinistros_enriched["n_pessoas"].fillna(0).astype(int)
sinistros_enriched["n_fatais_pessoas"] = sinistros_enriched["n_fatais_pessoas"].fillna(0).astype(int)
sinistros_enriched["n_veiculos"] = sinistros_enriched["n_veiculos"].fillna(0).astype(int)
sinistros_enriched["is_fatal_observado"] = sinistros_enriched["n_fatais_pessoas"] > 0

In [14]:
print(sinistros_enriched.shape)
sinistros_enriched[["id_sinistro","turno","n_pessoas","n_veiculos","n_fatais_pessoas","is_fatal_observado"]].head(5)

(535566, 55)

,id_sinistro,turno,n_pessoas,n_veiculos,n_fatais_pessoas,is_fatal_observado
0,2501575,NOITE,2,1,1,True
1,2462674,NOITE,1,0,1,True
2,2470843,TARDE,1,0,1,True
3,2483966,MANHA,1,1,1,True
4,2487581,MADRUGADA,1,1,1,True

In [15]:

sinistros_enriched.isnull().sum().sort_values(ascending=False).head(10)

tp_sinistro_colisao_traseira    535566
qtd_gravidade_ileso             535566
tp_sinistro_engavetamento       532488
tp_sinistro_colisao_outros      528496
qtd_onibus                      524147
tp_sinistro_capotamento         522546
qtd_bicicleta                   520420
qtd_veic_outros                 519372
qtd_caminhao                    516621
tp_sinistro_nao_disponivel      511752
dtype: int64

In [16]:
sinistros_enriched[
    ["is_fatal_sinistro", "is_fatal_observado", "n_fatais_pessoas"]
].head(10)

   is_fatal_sinistro  is_fatal_observado  n_fatais_pessoas
0               True                True                 1
1               True                True                 1
2               True                True                 1
3               True                True                 1
4               True                True                 1
5               True                True                 1
6               True                True                 1
7               True                True                 1
8               True                True                 1
9               True                True                 1

In [17]:
df_pessoas.head()

,id_sinistro,id_veiculo,cod_ibge,municipio,regiao_administrativa,tipo_via,tipo_veiculo_vitima,sexo,idade,gravidade_lesao,...,dia_sinistro,ano_mes_sinistro,data_obito,ano_obito,mes_obito,dia_obito,ano_mes_obito,local_obito,local_via,tempo_sinistro_obito
0,2473612,NaN,3509957,CANAS,SÃO JOSÉ DOS CAMPOS,ESTRADAS E RODOVIAS,AUTOMOVEL,MASCULINO,24.0,FATAL,...,1,2015/01,01/01/2015,2015.0,1.0,1.0,2015/01,VIA,PUBLICO,0.0
1,2460453,NaN,3543402,RIBEIRAO PRETO,RIBEIRÃO PRETO,VIAS URBANAS,None,MASCULINO,68.0,FATAL,...,3,2015/01,03/01/2015,2015.0,1.0,3.0,2015/01,ESTABELECIMENTO DE SAUDE,PUBLICO,0.0
2,2457878,NaN,3505500,BARRETOS,BARRETOS,ESTRADAS E RODOVIAS,CAMINHAO,FEMININO,54.0,FATAL,...,5,2015/01,05/01/2015,2015.0,1.0,5.0,2015/01,VIA,PUBLICO,0.0
3,2476044,NaN,3552205,SOROCABA,SOROCABA,ESTRADAS E RODOVIAS,None,FEMININO,43.0,NAO DISPONIVEL,...,9,2015/01,None,NaN,NaN,NaN,None,None,PUBLICO,NaN
4,2476271,NaN,3549904,SAO JOSE DOS CAMPOS,SÃO JOSÉ DOS CAMPOS,VIAS URBANAS,None,MASCULINO,27.0,NAO DISPONIVEL,...,10,2015/01,None,NaN,NaN,NaN,None,None,PUBLICO,NaN

In [18]:
df_pessoas.columns

Index(['id_sinistro', 'id_veiculo', 'cod_ibge', 'municipio',
       'regiao_administrativa', 'tipo_via', 'tipo_veiculo_vitima', 'sexo',
       'idade', 'gravidade_lesao', 'tipo_de_vitima',
       'faixa_etaria_demografica', 'faixa_etaria_legal', 'profissao',
       'grau_de_instrucao', 'nacionalidade', 'data_sinistro', 'ano_sinistro',
       'mes_sinistro', 'dia_sinistro', 'ano_mes_sinistro', 'data_obito',
       'ano_obito', 'mes_obito', 'dia_obito', 'ano_mes_obito', 'local_obito',
       'local_via', 'tempo_sinistro_obito'],
      dtype='object')

In [1]:

from etl.infosiga_prep import run_preparation

run_preparation(dt_ref=None)

ModuleNotFoundError: No module named 'etl'